### ISSUE TITLE
Glyph not found for rocket emoji on final slide (Windows)

### ISSUE THREAD

**Issue by jkxyz** [shaunlebron/solar-system-of-js#12]
Windows doesn't appear to support [this emoji](http://emojipedia.org/rocket/) which is used on the final slide. I'm reporting this from Windows 7 with Chrome.

I'll leave it up it to @shaunlebron to decide if this is worth the time to fix or remove. It's minor, but then again the glyph not found box is pretty ugly. It's clearly not a standard glyph or part of the Open Sans font.

**Comment by shaunlebron** [comment]
![screen shot 2015-04-15 at 10 10 25 am](https://cloud.githubusercontent.com/assets/116838/7161979/b1628626-e357-11e4-83ce-c5bae877454d.png)

thanks for taking the time to report this!

**Comment by jkxyz** [comment]
Cool, no problem. Great project! :smile:
